---
version: 1
formatters:
  brief:
    format: "[%(levelname)-8s] %(name)-20s: %(message)s"
  precise:
    format: "[%(levelname)-8s] %(name)-20s: %(message)s"
#    format: "[%(asctime)s %(levelname)-8s %(name)s::%(decorated_funcName)s (%(decorated_filename)s)]: %(message)s"
    datefmt: "%d.%m.%Y %I:%M:%S %p"
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : ERROR
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    level   : WARN
    formatter: precise
    filename: tslgen.log
    maxBytes: 1048576
    backupCount: 3
root:
  level: DEBUG
  handlers: ['console', 'file']
...