name: Generation Status

on:
  workflow_run:
    workflows: [push.yml]
    types: [completed]
    branches: [main]

jobs:
  generates-on-python:
    runs-on: ubuntu-latest
    steps:
      - name: Generation successful
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        run: | 
         exit 0
      - name: Generation failed
        if: ${{ github.event.workflow_run.conclusion != 'failure'}}
        run: | 
         exit 1

      
